/**
 * Content module emission — after a sync, writes a generated data module
 * (`.notion-to-site/index.js` + `index.d.ts`) so a project can
 * `import { pages, pagesBySlug } from './.notion-to-site'` with full types.
 */
import * as fs from 'fs'
import * as path from 'path'
import type { SyncedPage } from '../types.js'

export interface ContentTypeRef {
  /** Module to import the frontmatter type from, e.g. `'./types.js'`. */
  importPath: string
  /** The frontmatter type name, e.g. `'NotionContent'` or `'PostFrontmatter'`. */
  typeName: string
}

/**
 * Builds the generated content module as text. Pure — returns the `.js` and
 * `.d.ts` contents without touching the filesystem. Pages are sorted by slug
 * so the output is stable and diff-friendly across runs.
 */
export function buildContentModule(
  pages: SyncedPage[],
  typeRef: ContentTypeRef,
): { js: string; dts: string } {
  const sorted = [...pages].sort((a, b) => a.slug.localeCompare(b.slug))
  const data = sorted.map((p) => ({
    slug: p.slug,
    frontmatter: p.frontmatter,
    content: p.content,
  }))

  const js = [
    '// Generated by notion-to-site — do not edit by hand.',
    `export const pages = ${JSON.stringify(data, null, 2)}`,
    'export const pagesBySlug = Object.fromEntries(pages.map((p) => [p.slug, p]))',
    '',
  ].join('\n')

  const dts = [
    '// Generated by notion-to-site — do not edit by hand.',
    `import type { ${typeRef.typeName} } from ${JSON.stringify(typeRef.importPath)}`,
    '',
    'export interface ContentPage {',
    '  slug: string',
    `  frontmatter: ${typeRef.typeName}`,
    '  content: string',
    '}',
    '',
    'export declare const pages: ContentPage[]',
    'export declare const pagesBySlug: Record<string, ContentPage>',
    '',
  ].join('\n')

  return { js, dts }
}

/** Writes the generated content module (`index.js` + `index.d.ts`) into `dir`. */
export function emitContentModule(
  pages: SyncedPage[],
  dir: string,
  typeRef: ContentTypeRef,
): void {
  const { js, dts } = buildContentModule(pages, typeRef)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, 'index.js'), js, 'utf-8')
  fs.writeFileSync(path.join(dir, 'index.d.ts'), dts, 'utf-8')
}
