/**
 * Type emission — turns an introspected `NtsSchema` into a generated
 * TypeScript module: a Zod schema plus its inferred type. The module is
 * written into the consumer's project so their content is fully typed.
 */
import type { NtsSchema } from './introspect.js'
import { propertyToTypes } from './map.js'

/**
 * Generates the contents of the typed-content module. The output is a
 * self-contained `.ts` file exporting `<typeName>Schema` (a Zod object) and
 * `<typeName>` (the inferred type).
 *
 * Property keys are the verbatim Notion names — quoted, so spaces and emoji
 * are preserved faithfully rather than sanitized into something lossy.
 */
export function emitTypes(schema: NtsSchema, typeName = 'NotionContent'): string {
  const lines: string[] = []
  lines.push('// Generated by notion-to-site — do not edit by hand.')
  lines.push('// Regenerate with `nts types`; a typed `nts sync` also refreshes it.')
  lines.push("import { z } from 'zod'")
  lines.push('')
  lines.push(`export const ${typeName}Schema = z.object({`)
  for (const prop of schema.properties) {
    const { zod } = propertyToTypes(prop)
    lines.push(`  ${JSON.stringify(prop.name)}: ${zod},`)
  }
  // nts-managed frontmatter fields, added by the typed-mode sync (see cli.ts):
  // `_id` is the slug, `_notion_id` is the source Notion page id.
  lines.push('  _id: z.string(),')
  lines.push('  _notion_id: z.string(),')
  lines.push('})')
  lines.push('')
  lines.push(`export type ${typeName} = z.infer<typeof ${typeName}Schema>`)
  lines.push('')
  return lines.join('\n')
}
